# Copyright 2019 Alexander L. Hayes

# Meta:
#
#   This page is roughly organized according to "How often should this be changed?"
#   Topics near the top of the page may be changed semi-frequently, things near the
#   bottom may not want to be touched (there may even come a point where nobody
#   remembers what they do apart from whispers in the night).

# Publication Settings
publications:
  latest_news: "Papers accepted at CHI conference!" # Maybe pull from latest tweets?
  # investigators: Controls who shows up as buttons on the publications page.
  #   * Names must be listed exactly as they are in the ``publications.json``
  #   * They will appear on the page in the same order here
  investigators: ["Chia-Fang Chung", "James Clawson", "Kay Connelly", "Patrick C. Shih", "Katie A. Siek"]

# Collections
collections_dir: _collections
collections:
  json:
    output: true

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/IUProHealth
  - title: github
    url: https://github.com/IUProHealth

# Footer settings
footer:
  height: 150 # height in pixels
  copyright: Proactive Health Informatics at Indiana University, Bloomington

title: "ProHealth (Alpha)"
email: hayesall@iu.edu
description: >-
  We design, develop, and evaluate intelligent learning systems
  to empower lay people to better understand, manage, and
  improve their health.
baseurl: ""
url: ""
twitter_username: IUProHealth
github_username:  IUProHealth
feed:
  path: atom.xml

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

include:
  - .htaccess
  - _pages
exclude:
  - .bundle
  - Gemfile
  - LICENSE
  - vendor

permalink: pretty

color:
  primary-dark: '#990000'
  links: '#EDEBEB'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
