# Copyright 2019 Alexander L. Hayes

title: "ProHealth"
email: hayesall@iu.edu
description: >-
  We design, develop, and evaluate intelligent learning systems
  to empower lay people to better understand, manage, and
  improve their health.
baseurl: ""
url: ""
twitter_username: IUProHealth
github_username:  IUProHealth
feed:
  path: atom.xml

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

include:
  - .htaccess
  - _pages
  - ["_pages"]
exclude:
  - .bundle
  - Gemfile
  - LICENSE
  - vendor

permalink: pretty

color:
  primary-dark: '#990000'
  links: '#EDEBEB'

# Footer settings
footer: Proactive Health Informatics at Indiana University, Bloomington

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/IUProHealth
  - title: github
    url: https://github.com/IUProHealth

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
